### ISSUE TITLE
Header and Search

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#15]
Map (delete unless this replaces Layers in upper right
Add

- Home Page - Returns User to Home Page

- Click to Register
- Resource Link
Other?

Search Box
Add to left the text "Search by Address, Neighborhood, Zip""
Search Box
If not found (i.e., Capital Hill) return Not Exist; now if you hit enter with no record, it bounces to Landing page
Address if type 123 it picks up all numbers with 123  (i.e., 22123); focus on left string

**Comment by andreiradulescu** [comment]
For the address searching 123 anywhere in the string issue, I would leave that in. What if they search for a street name that occurs in the middle of the address? For example, 1540 Lawn Ave. If someone only puts in Lawn and the search only looks at the beginning, it would not find this address.

**Comment by JRDeLisle** [comment]
Andrei. That makes sense if you can't distinguish between the number component and the text. It's not that inconvenient as is.
