### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#17]
Disclaimer; make required I Agree before fading away and allowing entry
Search if not valid, it freezes; return something like: "Not found; please check spelling or go to map view." - like Parcel Veiwer

Search Land Bank Properties should be "Map Search"

**Comment by JRDeLisle** [comment]
Map search not work at this point.
![image](https://user-images.githubusercontent.com/8596328/31593535-e6788040-b1f4-11e7-9f47-fa6048a220ee.png)

**Comment by andreiradulescu** [comment]
This has been fixed.

**Comment by JRDeLisle** [comment]
Map search locked out now. Jim



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by andreiradulescu** [comment]
I would recommend clearing the cache of your current browser.
I've ran several searches just now and things seem to be coming back ok on
both the landing search and the top menu search.

Thanks,
- Andrei
