### ISSUE TITLE
Provide a method to display a Disclaimer

### ISSUE THREAD

**Issue by rlh-aagis** [rlh-aagis/vacant2vibrant#2]
JDelisle \ BNevers to provide disclaimer to be used for this project.

**Comment by JRDeLisle** [comment]
We will work with Tony Luppino and perhaps Gregg Lombardi. Gregg feels we can get help from a law firm pro bono. He also things "good faith efforts" will go a long way.

**Comment by JRDeLisle** [comment]
Great
