### ISSUE TITLE
Inconsistent Data: Property Display vs. APN County Site

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#26]
Hi. First of all, great progress. I'm really excited about what you're doing. The link county data is great in that it returns a picture and some other useful information. One problem I noted is that there is an inconsistency between the data we got from the Open Data portal and the current county data. Here is an example.
![image](https://user-images.githubusercontent.com/8596328/31640027-92da1e5a-b2a1-11e7-82de-b511b73e37ec.png)
Not sure which is more current but the link is so good we should opt for that (I think). I'll try to figure out the differences but thought I'd point it out.

**Comment by rlh-aagis** [comment]
Send Andrei image URL to view picture, to be added to the bottom of column 2 on property pop-up:

[http://maps.jacksongov.org/AscendPics/Pictures/27-210/27-210-11-21-00-0-00-000_AA.jpg](url)

**Comment by JRDeLisle** [comment]
This deals with age of County data. Longer term issue trying to fix via new data access strategy.
