### ISSUE TITLE
Various "Fixes"

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#33]
I have demonstrated the site to a couple of individuals and picked up some additional insights. While some of these are embedded in other issues, given the timing I thought it best to list them and try to cross-reference issues later. 

- Register. Still very slow to send confirmation; we will need that fixed before showing many others.

- Landing Page. Map Search not clear where it "lands;" zoom out and pick a central spot.

- Action. Not clear what to do on map; perhaps add a click to select to get them started; after first, it should be clear.

- Area. We defaulted to Neighborhood for unregistered users; I think that's overwhelming in the sense they have to manually zoom out to see the boundaries. I think we should go back to .25 and differentiate registered by adding more data. We could leave the option to see neighborhood stats in addition to .25 Brent, what are your thoughts on this?

- Neighborhood/.25. When we show neighborhood, the .25 mile grey-out still occurs; turn off and show color code for all in neighborhood.

- Icons/Sold. Indicate $ signifies sold properties.

- Register. The Gender should be a drop to avoid typos and other errors; Purchased before with Yes/No okay but may not need the Have you purchases....

- Login. Need a "Forgot Password" option to reset.  I can't get in and it says "Error: Email address/password are incorrect." I don't know which one which would help along with Help with PW

- Search by Zip. Not clear the answers are zips; it indicates 64101 Kansas City, 64102 Kansas City The zip does seem to auto scale better...  The zips are not restricted to ones with LB properties. Also, still use grey-out for .25 when in Zip

- Manual Next Search. There should be an option when you are in Zip or NEIGH mode to pick a property to left/right/north/south and have it highlight and summarize that boundary.

- Back/previous view. As discussed this would be great. Also,

**Comment by JRDeLisle** [comment]
Hi. Sorry, I accidentally closed this. New question; on property display could we add a link to the Parcel Viewer for the properties? That would pull up the legal descriptions and additional data.  The APN link is great but only shows some data.

**Comment by andreiradulescu** [comment]
Issues fixed with the following notes:
Set the area to default to 0.25 mile search even for unregistered users. After logging in, they see more data. 
Pulled manual next search into a separate issue since it's a new feature and more involved.

**Comment by JRDeLisle** [comment]
Great
