### ISSUE TITLE
Replace Jackson Cty Parcel Viewer with KCMO Parcel Viewer

### ISSUE THREAD

**Issue by rlh-aagis** [rlh-aagis/vacant2vibrant#37]
![image](https://user-images.githubusercontent.com/3280502/32584836-0e6c0332-c4c0-11e7-8862-45ec67551b2e.png)

**Comment by rlh-aagis** [comment]
How to pass Property ID to KCMO Parcel Viewer and view automatically - pass using KIVAPIN. Example:

[http://maps.kcmo.org/apps/parcelviewer/?kiva=260528]

**Comment by JRDeLisle** [comment]
Hi Ron. Didn’t see the issue in GitHub but it looks like it works. Do I need to pull KIVA pins? Jim

James R. DeLisle, Ph.D.
Director, Academic Real Estate Programs
Associate Professor, Henry W. Bloch School of Management
University of Missouri-Kansas City
5110 Cherry Street, Suite 217
Kansas City, MO 64110

Office: (816) 235-6288 / Cell: (913) 747-8580
Email contact: DeLisleJ@umkc.edu<mailto:DeLisleJ@umkc.edu>
Personal JRD Website: www.JRDeLisle.com<http://www.jrdelisle.com/>
LinkedIn Contact Name: Jim DeLisle

Click Logo for White Center Website
[1LewisWhite_v1]<http://bloch.umkc.edu/lwrec/default.aspx>                           Check our new
                                                        Master of Science in Entrepreneurial Real Estate<http://bloch.umkc.edu/graduate-program/mere/default.aspx>
                                                                                     (MSERE) Spring 2018 Openings

**Comment by JRDeLisle** [comment]
We have both but Parcel Viewer doesn't work. This still doesn't work but might not be fixable with the pause for the disclaimer.

**Comment by rlh-aagis** [comment]
Added lb_kiva_parcel table containing Address, Kiva Pin and Jackson Cty Parcel ID.

**Comment by andreiradulescu** [comment]
Updated Kansas City Parcel Viewer link to include Kiva Pin (where available)

**Comment by JRDeLisle** [comment]
Hi. I see it works; at first I was looking for the address in the Enter Address bar. Great job!
