### ISSUE TITLE
Search Address; find NEIGH, then Register; not switch to Radius

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#44]
If I search for address unregistered; find house and Neighborhood stats; register and then want to see radius, the Search doesn't work.
![image](https://user-images.githubusercontent.com/8596328/32585957-9aa66932-c4c5-11e7-9c9d-ef4318fee69c.png)

If I copy and paste address over itself, it does work or if I reenter address but won't if just hit search button.

**Comment by andreiradulescu** [comment]
This seems to work when I last used it. Also ensure that you completely clear your browser's cache in case it could be a caching issue.
