### ISSUE TITLE
Background Maps

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#45]
The background maps seem redundant; I'd like to see the satellite back.
![image](https://user-images.githubusercontent.com/8596328/32586095-63b5e794-c4c6-11e7-8e02-748de56c13d5.png)

**Comment by andreiradulescu** [comment]
I have added back in the nicer ESRI street map and world imagery, and left in one of the OpenStreetMap maps.

**Comment by JRDeLisle** [comment]
Looks good. On an Android, the legend does not display which is probably good given limited screen size. However, the map options stay displayed and take up a lot of screen. Can we collapse those as we do with the others?

**Comment by JRDeLisle** [comment]
I think the Open StreetMAP_Mapnik is superior with showing churches, green space, etc. to the Esri World which is redundant. I like the World Imagery (maybe call it Satellite or Aerial) but think we should replace the Esri World with the Open Topo we had earlier.

**Comment by JRDeLisle** [comment]
Looks great. Jim
