### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#46]
While we know we need some work on this (Phase 2) we might want to see if we can translate a bit more. As of now, only the Home Button Changes.
![image](https://user-images.githubusercontent.com/8596328/32586209-f190d77c-c4c6-11e7-8be6-d50057608178.png)

**Comment by andreiradulescu** [comment]
Updated all menus and labels except the user login / registration / activation / forgot password dialogs.

**Comment by JRDeLisle** [comment]
Great. I'll check later so let me know a good time. I haven't asked my students yet so let me know when you think we need fresh eyes.  Thanks for all the work.   Jim



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by JRDeLisle** [comment]
Nice Job. I just checked and Area Stats are translated; need to do same for mouse over I. Great.

**Comment by JRDeLisle** [comment]
This works; we have to check on "official" translation if tied to UMKC.
