### ISSUE TITLE
Link to Land Bank

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#62]
Not all have links; 2816 Olive St, 2715 Brooklyn AVE, 2637 Garfield....

Others have it and it works great; not clear why missing. Here is one the works 2511 Montgall Ave

**Comment by andreiradulescu** [comment]
That was by design. Only available properties have links, since the sold
ones don't even have pages on the land bank website. I thought better not
to show those instead if having a broken link.

**Comment by JRDeLisle** [comment]
Great. Thanks. Jim

James R. DeLisle, Ph.D.
Director, Academic Real Estate Programs
Associate Professor, Henry W. Bloch School of Management
University of Missouri-Kansas City
5110 Cherry Street, Suite 217
Kansas City, MO 64110

Office: (816) 235-6288 / Cell: (913) 747-8580
Email contact: DeLisleJ@umkc.edu<mailto:DeLisleJ@umkc.edu>
Personal JRD Website: www.JRDeLisle.com<http://www.jrdelisle.com/>
LinkedIn Contact Name: Jim DeLisle

Click Logo for White Center Website
[1LewisWhite_v1]<http://bloch.umkc.edu/lwrec/default.aspx>                           Check our new
                                                        Master of Science in Entrepreneurial Real Estate<http://bloch.umkc.edu/graduate-program/mere/default.aspx>
                                                                                     (MSERE) Spring 2018 Openings
