### ISSUE TITLE
Home Page Background Image

### ISSUE THREAD

**Issue by JRDeLisle** [rlh-aagis/vacant2vibrant#63]
We need a different background image; the new one is misleading and similar to the Land Banks where it shows properties not in the Land Bank. I think a map of KCMO or the region might be better.  We could roll back to prior unless you have a different idea.

**Comment by andreiradulescu** [comment]
Updated the landing page background image to a grayed out map overseeing the land bank area.

**Comment by JRDeLisle** [comment]
Looks great; thanks. At some point this weekend or so, I'll write up a Help or similar since some people hitting our home page may not know what to do. Let me know if you have any questions or need anything from me.
